# -*- coding: utf-8 -*-
"""working project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1quxM5HodJiZppsX7useFoy_YTxv3bPsi
"""

!pip install padelpy
!pip install rdkit padelpy

import pandas as pd
import numpy as np
import matplotlib as mpl
data = pd.read_excel("/content/CNSData(940) - 複製 - 複製.xlsx")

from padelpy import from_smiles
from rdkit import Chem
from rdkit.Chem import Descriptors
from pathlib import Path

above_900=data[data["ID"]>900]
data = pd.DataFrame(data)
data.head()

data["smiles"][0]

sample = data["smiles"][0]
# print(sample)
# sample=sample.to_string()
# type(sample)

descriptors = from_smiles(sample)
select_data=pd.DataFrame([descriptors])
print(select_data)

table = pd.DataFrame()
for i in range(10):
  sample = data["smiles"][i]
  descriptors = from_smiles(sample)
  select_data=pd.DataFrame([descriptors])
  if i>0:
   table=pd.concat([table,select_data])
  else:
    table=select_data
print(table)

filepath = Path('/content/drive/MyDrive/workingproject.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
table.to_csv(filepath)